Repository getdokan/wepos, pull requests merged in 2021-11, with the labels that each got.

#80 Support for other decimal separator chars + fix rounding issue for discounts
  assets/src/frontend/components/Home.vue
  assets/src/frontend/components/PrintReceiptHtml.vue
  assets/src/utils/Mixin.js
  assets/src/utils/lodash.js
Labels: QA Approved, Dev Review Done

#84 fix: npm vulnerabilities
  package-lock.json
Labels: Needs Dev Review, QA Approved

#85 fix: wePOS settings page font fallback issue
  assets/css/style.css
  assets/css/style.css.map
  assets/less/style.less
Labels: Needs Dev Review, QA Approved

#87 add: pos tab view responsiveness for cart content
  assets/src/frontend/components/Home.vue
Labels: Needs Dev Review, QA Approved

#89 add: black friday promotion
  includes/admin/LimitedTimePromotion.php
Labels: Needs Dev Review, QA Approved

#88 Update/core structure
  assets/src/utils/store/modules/Cart.module.js
  composer.json
  composer.lock
  includes/Frontend.php
  includes/Gateways/Cash.php
  includes/Gateways/Manager.php
  includes/REST/CustomerController.php
  includes/REST/PaymentController.php
  includes/REST/ProductController.php
  includes/REST/SettingController.php
  includes/REST/TaxController.php
  includes/admin/Admin.php
  includes/admin/Products.php
  includes/admin/Settings.php
  includes/functions.php
  templates/woocommerce-dependency-notice.php
  wepos.php
Labels: Needs Dev Review, QA Approved

#90 fix: thermal printer unclear text
  assets/src/frontend/components/PrintReceiptHtml.vue
Labels: Needs Dev Review

#91 fix: lodash findindex
  assets/less/style.less
  assets/src/utils/lodash.js
  includes/admin/LimitedTimePromotion.php
Labels: QA Approved
