Repository getdokan/wepos, pull requests merged in 2022-11, with the labels that each got.

#95 Feat/my account view pos
  includes/Frontend.php
Labels: Enhancement, QA Approved, Dev Review Done

#116 enhance: Added all decimal separator support as per wooCommerce settings to put a discount or adding a fee in POS settings
  assets/src/frontend/components/FeeKeypad.vue
  assets/src/frontend/components/Home.vue
Labels: QA Approved, Ready to Merge, Dev Review Done

#121 enhance: Update webpack to v5
  .babelrc
  bin/zip.sh
  includes/Admin/Admin.php
  includes/Assets.php
  package-lock.json
  package.json
  webpack.config.js
Labels: QA Approved, Ready to Merge, Dev Review Done

#123 fix: Variable product visible even no attributes used
  assets/src/frontend/components/Home.vue
Labels: QA Approved, Ready to Merge, Dev Review Done

#124 fix: Broken layout of smaller width print receipt
  assets/src/frontend/components/PrintReceiptHtml.vue
Labels: QA Approved, Ready to Merge, Dev Review Done

#127 chore: version replace
  bin/scripts/version-replace.js
  package-lock.json
  package.json
Labels: Dev Review Done

#128 refactor: set order created via wepos
  includes/Common.php
  includes/Frontend.php
  includes/Gateways/Cash.php
  wepos.php
Labels: Dev Review Done, Needs Dev Review Only
